### PR TITLE
Fix ignored files when different project path

### PR DESCRIPTION
**Pull request by dubreuia**

### CODE REVIEW

**Comment by dubreuia** [comment]
@dorkbox I took only commit ae7a25e and modified it a bit : you deleted the method com.dubreuia.Component#isActive(com.intellij.openapi.editor.Document), so I restored it. 

I'm wondering if the method isActive duplicates the check you do with `DataManager.getInstance().getDataContextFromFocus().getResult()` ? Is it why you removed krasa's methods ?

**Comment by dorkbox** [comment]
Yes, it's a duplicate.

**Comment by dorkbox** [comment]
I forgot to push my latest -- as there are issues with not having a document selected and null pointers.

**Comment by dorkbox** [comment]
I think that I've also found a better method to check which is the active document -- it turns out that if something else has focus, it won't run the save actions, and there are some null pointers floating around . I think the "Fast Scroll" plugin behaves the way we want -- where the currently selected document is the one modified. I'm looking into that right now

**Comment by dubreuia** [comment]
I merged 7d8b75 in master. Keep me posted if you find a better solution.

**Comment by dorkbox** [comment]
It turns out that the Fast Scroll plugin uses similar hooks as Save Actions does.  

I should point out that ```DataManager.getInstance().getDataContextFromFocus().getResult()``` is the recommend way to get the active context, from jetbrains staff -- I found it while reading their forums.  Then from there we can get the correct project and document in a straightforward way.

**Comment by dubreuia** [comment]
OK I'm closing the PR as this is our current implementation.

And I tested this morning, krasa's isActive method is needed too so that the plugin executes on frame deactivation too. If it not there it will always skip the plugin, except on the Save All action, which is not what we want.

You might want to check the current master, it is quite far from yours.

**Comment by dorkbox** [comment]
Ah, excellent point about isActive, I didn't try that. Now that the issues I was having are fixed (even though my master has drifted far from yours), I'll be dropping my fork and switching back. Thanks for merging the fixes. :+1: Now to figure out how to add missing ```@Override``` annotations on save action...

**Comment by dubreuia** [comment]
"Now to figure out how to add missing @Override annotations on save action..."

About that, I was thinking of supporting any inspections. See https://github.com/dubreuia/intellij-plugin-save-actions/issues/9, there is some code in there too.

**Comment by dorkbox** [comment]
Great! I'll submit a PR for you when I get that added. On the topic of inspections, adding the ```this.``` prefix is also one that I would want.

**Pull request closed without merging**
