### PR TITLE
#165 On-save action to generate SerialVersionUID for Serializable

### PR DESCRIPTION
**Pull request by rw00**

### CODE REVIEW

**Comment by dubreuia** [comment]
Thanks I'll check it out this week

**Comment by rw00** [comment]
Hi @dubreuia  , 
Should I do something about the codecoverage? 
The codecov/patch check failed

**Comment by dubreuia** [comment]
Merged.

I've added a test `com.dubreuia.integration.JavaIntegrationTest#should_generateSerialVersionUID_generates_serial_version_uid_for_serializable_class` but I can't make it work.

**Comment by dubreuia** [comment]
@rw00 Nothing to do about the code coverage, it shouldn't be activated on PR (I deactivated it in master).

**Comment by dubreuia** [comment]
Added to 1.1.0 draft https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/untagged-a225d39f390573a2793e

**Comment by rw00** [comment]
@dubreuia  is the test working now? I tested it from IntelliJ itself and it worked

**Comment by dubreuia** [comment]
Thanks a lot @rw00 !

**Comment by dubreuia** [comment]
@rw00 Actually it works when tested manually, but the integration test fails, I don't know why. There are some other tests like that. Check `com.dubreuia.integration.JavaIntegrationTest`, some are `@Disabled`

**Comment by rw00** [comment]
@dubreuia  I believe it's generating a different SerialVersionUID on each run so you can't really test it this way. Or we will have to implement a different type of test

**Comment by dubreuia** [comment]
@rw00 That's what I though first, but it seems it isn't the case. From what I understand, it generates an ID based on the class serialization content, so if you don't change the class signature (fields, methods, etc.), it won't change the ID. You can even change the body of the methods, it will still generate the same ID. I think: same ID means serialization / deserialization possible.

That being said, the test do not work in the sense that the serialVersionUID is never inserted. I need to debug the test framework to see why it isn't working.

**Pull request merged**
