### PR TITLE
Add toggleable action to activate/deactivate Save Actions from the "F…

### PR DESCRIPTION
**Pull request by markiewb**
Add toggleable action to activate/deactivate Save Actions from the "Find Actions..." dialog

### CODE REVIEW

**Comment by markiewb** [comment]
This is somehow related to #59

**Comment by markiewb** [comment]
@dubreuia: Please review and merge. PS: I proposed also other small PRs

**Comment by dubreuia** [comment]
Thanks a lot I wanted to add this one for a while!

I'll check the others too

**Comment by dubreuia** [comment]
Thanks @markiewb

**Pull request merged**
