### PR TITLE
#135 Supporting tightening access to class members

### PR DESCRIPTION
**Pull request by rw00**

### CODE REVIEW

**Comment by rw00** [comment]
there's an issue in my repository. for some reason, git pull is NOT getting latest changes!!!

**Comment by dubreuia** [comment]
Thanks I'll check it out this week.

**Comment by dubreuia** [comment]
Yeah @rw00 your branch history is a bit of a mess.

Merged to master

**Comment by dubreuia** [comment]
I've added documentation and tests don't forget it next time!

**Comment by dubreuia** [comment]
Thanks a lot @rw00!

**Comment by dubreuia** [comment]
Added to 1.1.0 draft https://github.com/dubreuia/intellij-plugin-save-actions/releases/edit/untagged-f1564d8d8d0af293dea8

**Comment by rw00** [comment]
@dubreuia  yes there was an issue with the repository. I had to delete it and `git init` again so that `git pull` works again!

**Comment by dubreuia** [comment]
Like that?

git01

**Comment by rw00** [comment]
hahahahaha well, I do know some git but yeah in the end I had to do this "easy" way to unblock myself

**Comment by dubreuia** [comment]
:smile:

**Pull request merged**
