### PR TITLE
fix error when creating new java file

### PR DESCRIPTION
**Pull request by zhujk**
Signed-off-by: zhujk <zhujk@outlook.com>

### CODE REVIEW

**Comment by dagger** [comment]
Thanks so much for this, I had just cloned and ready to code. Saw your pull request and I'm pretty excited! 👍  to @zhujk

**Comment by zhujk** [comment]
It is my pleasure. @dagger

**Comment by dubreuia** [comment]
Thanks a lot @zhujk! Merged and closed, I'll release version 0.12

**Comment by dubreuia** [comment]
Done

- https://github.com/dubreuia/intellij-plugin-save-actions/releases/tag/v0.12
- https://plugins.jetbrains.com/update/index?pr=&updateId=27845

**Pull request merged**
