### PR TITLE
Add option to "Use blocks in if/while/for statement"

### PR DESCRIPTION
**Pull request by markiewb**
Like requested in https://github.com/krasa/EclipseCodeFormatter/issues/10

### CODE REVIEW

**Comment by markiewb** [comment]
@dubreuia: Please review!

**Comment by dubreuia** [comment]
Sorry I forgot about this one, I'll add it ASAP.

**Comment by markiewb** [comment]
@dubreuia: I rebased my pull-request due to the recent changes in 0.17. Please integrate!

**Comment by dubreuia** [comment]
I'm so sorry @markiewb I forgot about this one again :(, don't hesitate to send me a message when that happens. Thanks a lot for your contributions this is very much appreciated.

And thanks for rebasing on 0.17, I just built the plugin with your modifications, I'll test it this afternoon at work and merge to master at the end of the day.

This a big release because we'll jump from 0.16 to 0.18 with multi-editor support, but people have used 0.17 in other products for I'm fairly confident...

**Comment by dubreuia** [comment]
This one has been open for 2 months I'm way too slow. Thanks again, merged and published in jetbrains repo

**Pull request closed without merging**
