### PR TITLE
Add option to "ignore compile errors" (disabled by default)

### PR DESCRIPTION
**Pull request by markiewb**
See https://github.com/dubreuia/intellij-plugin-save-actions/issues/76

2017-04-10_09h22_58

### CODE REVIEW

**Comment by xinkunZ** [comment]
SO NICE!!

**Comment by dubreuia** [comment]
Hey thanks for the PR @markiewb! I should have some time this weekend to merge it.

I'll rename it to "Don't reformat if compile errors" if you don't mind.

**Comment by markiewb** [comment]
That would be great. Do not include "format" in the label, because other
actions like Rearrange or Compile is also affected.

Den 12 apr. 2017 10:49 fm skrev "Alexandre DuBreuil" <
notifications@github.com>:

**Comment by dubreuia** [comment]
I have not forgotten this PR, I should have time soon to merge it. Thanks

**Comment by dubreuia** [comment]
Merged in master

**Pull request closed without merging**
