### PR TITLE
Import existing Eclipse .epf file #81

### PR DESCRIPTION
**Pull request by markiewb**
@dubreuia: Please review the fix for #81! 

Please not that the EPF-support is limited to Java only, as you can see in the configuration-prefix ```org.eclipse.jdt.ui```. Other types like those for JavaScript ```org.eclipse.wst.jsdt``` are not supported (yet).

epfconfiguration
default
error message

### CODE REVIEW

**Comment by markiewb** [comment]
At https://github.com/markiewb/intellij-plugin-save-actions/releases/tag/v22withEPF you can find a SNAPSHOT-build

**Comment by dubreuia** [comment]
Thanks for your PR I'll review it asap.

If I understand correctly: it won't sync with the .epf file, but just import it once when you close the settings page for the first time?

**Comment by markiewb** [comment]
@dubreuia: No. That is not correct. While saving an edited file, the plugin will load the configuration file, provide a ```Storage``` instance based on the settings in the file and uses this instance as the base for formatting. So once configured, external changes to the configuration file will alter the formatting behaviour.

Perhaps we should add a clarifying label to the dialog to describe this feature for the end-user.

**Comment by dubreuia** [comment]
OK I see. Yes we should add at least a clearer label in the settings pages, and some documentation in the README.

**Comment by markiewb** [comment]
@dubreuia: What is next?

**Comment by dubreuia** [comment]
Sorry I'm in vacation I'll finish the code review when I come back this
weekend

On Sep 20, 2017 15:27, "markiewb" <notifications@github.com> wrote:

@dubreuia <https://github.com/dubreuia>: What is next?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/dubreuia/intellij-plugin-save-actions/pull/106#issuecomment-330955815>,
or mute the thread

**Comment by dubreuia** [comment]
I haven't forgotten this one, too much work right now

**Comment by dubreuia** [comment]
I just merged this, but I made a lot of modifications on your code. Can you test it @markiewb please? I'll wait for your testing before release

[save-actions_0.22-RC.zip](https://github.com/dubreuia/intellij-plugin-save-actions/files/1405151/save-actions_0.22-RC.zip)

**Pull request merged**
