### PR TITLE
Add a global configuration used by default for all projects

### PR DESCRIPTION
**Pull request by le-yams**
Hi,

This is kind of related to #120 so there is a PR to add a global configuration to be used by default for all projects (I love your plugin but as I'm working with a lot of projects this is a must have for me ^^).

This is my first IntelliJ plugin dev so it is probably not the state of the art, all your comments will be very welcome!

I added a "useGlobalConfiguration" action which is only displayed in project configuration.

The Storage class is now an abstract class to factorize code. GlobalStorage and ProjectStorage are the persisted States.
The StorageFactory checks which storage to return.
I made the storage having the useGlobalConfiguration Action in default constructor so all projects use global configuration by default. 
This seems a bit dirty to me and there might be a cleaner way using Actions properties (I saw there already is a "defaultValue" property which is very similar to what I needed but it is use for configuration ui first startup and I needed this to be the default even if the user doesn't open the configuration ui).

The ui Configuration class is also abstract now. The ProjectConfiguration and GlobalConfiguration basically only provide the storage and the display name (My lack of inspiration made me put "Save Actions (Global)" for the global configuration).

I updated the integration tests so it tests both project and global storage.

Hope you'll like it :)

Regards,
Yann

### CODE REVIEW

**Comment by dubreuia** [comment]
Hey @le-yams, I really appreciate the PR, thanks. I just read though it and it looks pretty clean, gg!

Two comments:

- Duplicated tests between project and global settings
- No documentation (README + plugin.xml) update

I have a lot of work right now but I'll try to test it asap

**Comment by le-yams** [comment]
Yeah I was not happy with the duplicated tests but I was having an issue using parametrized tests to solve it. Actually it was me not seing the elephant in the room (note for later, do not make a PR at 2am -___-' ). I just pushed a refactor for it, 

I'll try to update the documentation quickly.

**Comment by le-yams** [comment]
Documentation updated.

**Comment by dubreuia** [comment]
Great thanks. I'm unsure about the `StorageTest` annotation, but if it works I'm okay with it.

Give me some time to review and test.

**Comment by le-yams** [comment]
I set this annotation because in addition to summarizing the 2 junit annotations (@ParameterizedTest+@EnumSource and so make it more consise for each test), I though it add some intent to the code. 
You can rename it or even remove it and use directly the two junit annotations if you don't like it. It really is a tiny detail.

**Comment by dubreuia** [comment]
I see what you wanted to do. JUnit5 and easy custom test annotations are quite new, I'm unsure what is the recommended pattern on this (if any). My two cents is `@StorageTest` will talk less to someone reading the code then the combination of two known annotations.

I'm nitpicking btw, this PR is great, and I'm ok with the annotation. I'll review soon.

**Comment by le-yams** [comment]
I agree that it might not be very clear for someone new to JUnit5.

I'm all for nitpicking in codereview ;-) and I'm very glad to contribute!

**Comment by dubreuia** [comment]
Hey @le-yams just to let you know I haven't forgotten this, I just had a lot of work recently and didn't take the time to review. I'll check it you asap.

**Comment by dubreuia** [comment]
I started the review on https://github.com/dubreuia/intellij-plugin-save-actions/tree/le-yams-master

I'd like the settings to have a single root element of "Save Actions", then under that project and global:

- "Other Settings"
    - "Save Actions"
        - "Global settings"
        - "Project settings"

There's a lot to test in that branch it will take me some more time

**Comment by dubreuia** [comment]
I'm pretty sure EPF settings do not work with global settings (see hard coded constructor com/dubreuia/model/java/EpfStorage.java:44), either make it work or deactivate EPF with global settings.

**Comment by le-yams** [comment]
Hi Alexandre,

Sorry for the late reply, I currently don't have much free time ^^. I'll try to work on it asap.

> I'd like the settings to have a single root element of "Save Actions", then under that project and global:
> 
>     * "Other Settings"
>       
>       * "Save Actions"
>         
>         * "Global settings"
>         * "Project settings"
>

I didn't know it was possible and like that very much, I'll take a look at it :)


> I'm pretty sure EPF settings do not work with global settings (see hard coded constructor com/dubreuia/model/java/EpfStorage.java:44), either make it work or deactivate EPF with global settings.

As I don't have much time to investigate, I'll desactivate it for now.

Regards,
Yann

**Comment by dubreuia** [comment]
Thanks I'll look into it ASAP

**Comment by le-yams** [comment]
Hi Alexandre,

Any news on this PR ?

Regards,
Yann

**Comment by dubreuia** [comment]
Hello @le-yams, I'm so sorry this is taking taking so much time, this is a big PR to review and I keep postponing it. I'll continue the review today and let you know.

**Comment by dubreuia** [comment]
I'm not a big fan of the UI, it would have been better to make a global / project UI like in the following screenshot.
Screenshot from 2019-11-23 13-28-31

**Comment by dubreuia** [comment]
The main problem I have is that we cannot (AFAIK) deactivate the checkboxes that aren't used. If I uncheck the "use global settings", the global settings can still be checked, which is confusing.

**Comment by dubreuia** [comment]
I'm refactoring your code right now. I think I like the idea of having global settings, but I feel like it should be the opposite of what we've done: in the global settings, which is loaded by default, we define a property "use project settings" that overrides the global settings. The "use project settings" should be activated by default so that we support older versions of the plugin (this is the current default behavior).

- Storage (abstract class)
    - GlobalStorage (all storage info + "use project settings", loaded by default)
    - ProjectStorage (all storage info, loaded of "use project settings" is selected)

**Comment by dubreuia** [comment]
I've made the changes, but I have an error during execution. Not sure what I'm trying to do is possible... Do you know how to fix that?

```
2019-11-23 14:57:54,200 [ 255086]  ERROR - r.PlatformComponentManagerImpl - com.dubreuia.model.GlobalStorage is registered as application service, but requested as project one 
java.lang.Throwable: com.dubreuia.model.GlobalStorage is registered as application service, but requested as project one
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:296)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at com.dubreuia.model.StorageFactory.lambda$static$0(StorageFactory.java:12)
	at com.dubreuia.model.StorageFactory.getStorage(StorageFactory.java:31)
	at com.dubreuia.model.StorageFactory.lambda$static$1(StorageFactory.java:20)
	at com.dubreuia.model.StorageFactory.getStorage(StorageFactory.java:31)
	at com.dubreuia.core.component.SaveActionManager.getStorage(SaveActionManager.java:105)
	at com.dubreuia.core.component.SaveActionManager.guardedProcessPsiFiles(SaveActionManager.java:143)
	at com.dubreuia.core.action.ShortcutAction.actionPerformed(ShortcutAction.java:33)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:266)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:283)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:602)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:655)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:654)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:472)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:828)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:773)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I've also added a `ConfigurationPanel` for the checkbox:

Screenshot from 2019-11-23 15-01-35

**Comment by dubreuia** [comment]
@le-yams Can you check the content of the https://github.com/dubreuia/intellij-plugin-save-actions/tree/le-yams-master branch and let me know what you think?

**Pull request closed without merging**
