### PR TITLE
Fixed Bug #246

### PR DESCRIPTION
**Pull request by JavaFactoryDev**
+ ForceReload (Fixes Issue #246 and #209 )
-> Improved readability of Code in BuildProcessor

Comment:
All changes have been tested. Used an own fork of this plugin & everything worked perfectly fine.

### CODE REVIEW

**Comment by dubreuia** [comment]
Hello @JavaFactoryDev and thanks a lot for submitting this PR. 

I have 2 issues with the branch you've submitted:

- You haven't followed the code style listed in the contributing guide: https://github.com/dubreuia/intellij-plugin-save-actions/blob/master/CONTRIBUTING.md. We cannot have a part of the code that's formatted in a style different than the other parts.
- You have submitted a single commit with both style change and content change. This is really hard for the reviewer since he'll need to find in the diff what is actually fixing the issue.

Please re-submit the PR

**Comment by kangarko** [comment]
@JavaFactoryDev thanks for putting in the effort! To get this approved it seems you'll have to comply with the code style policy, would you please be able to do that? Thanks!!

**Comment by kangarko** [comment]
@JavaFactoryDev do you have any update on this? :)

@dubreuia can you just make the style changes yourself? The user is clearly lots of putting effort, all you need is some minor adjustments and then pull it to the final version.

**Comment by dubreuia** [comment]
Hello @kangarko. Sure I can make the changes myself, I'll do it when I have time, and I'll test the feature at the same time. Maybe December if all goes well, or January if not. Thanks.

**Comment by JavaFactoryDev** [comment]
I will just resubmit the pr

**Comment by kangarko** [comment]
Thanks to both of you! Alright dubreuia, take your time.

JavaFactoryDev when you have a fork and binaries that users can conveniently install to their IntelliJ just post in our Fb group ;)

**Comment by kangarko** [comment]
@JavaFactoryDev when I try the version from http://thewarking.de/ideapl.jar by installing it from the disk, I am getting the following error a 

Using the latest stable IDEA
a

**Comment by JavaFactoryDev** [comment]
Yeah, I just made this build compatible with my IntelliJ UE edition. I will fix this. Let's talk on the next call ^^.

**Comment by kangarko** [comment]
Awesome thanks! <3 I got this working by editing plugin.xml file in MANIFEST by lowering the <since> option to 190

**Pull request closed without merging**
