### PR TITLE
#129 vertically aligning settings panels

### PR DESCRIPTION
**Pull request by rw00**
Please note that the code changes were formatted with `config/code-style.xml`

### CODE REVIEW

**Comment by dubreuia** [comment]
Hey @rw00, thank you for your PR

- You haven't imported the `config/code-style.xml` properly, there are `*` imports in your code
- The `GridBagLayout` adds space between its elements, it's ugly for big settings window pane (see screenshot), and not consistent with other Intellij panels. I've tried various configuration but can't make it work.

screenshot from 2018-08-16 13-44-27

**Comment by rw00** [comment]
@dubreuia  Please remove `c.weighty = 1;` and check whether it fixes the gap-between-components issue

**Comment by rw00** [comment]
@dubreuia  I fixed the issue. I will submit tonight

**Comment by dubreuia** [comment]
image

**Comment by rw00** [comment]
The tests failed on appveyor: 
```
com.dubreuia.integration.CommonIntegrationTest > should_reformat_with_shortcut_produces_indented_file_on_shortcut() FAILED
    java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/projects/intellij-plugin-save-actions/build/classes/java/test-instrumented/
```

**Comment by dubreuia** [comment]
LGTM. Thanks a lot @rw00 

Don't worry about appveyor, I need to fix this but as long as travis passes we're good.

**Pull request merged**
