### PR TITLE
Add option for  triggering  save actions by short cut #63

### PR DESCRIPTION
**Pull request by edeknede**
I created a new option for running save actions with a shortcut instead of triggering automatically by intellij save mechanism. By the way the short cut is currently configured to "CTRL + SHIFT + S"
image

It is implemented as an Action and placed into the menu like the following:
image

Please have a look at it and let me know if i can improve it.

### CODE REVIEW

**Comment by edeknede** [comment]
The only change i made in the META-INF/plugin.xml was the new Action.

**Comment by markiewb** [comment]
I guess what you are looking to aim for can be achieved by a custom cleanup
profile, isn't?

Den 10 okt. 2017 3:39 em skrev "edeknede" <notifications@github.com>:

**Comment by edeknede** [comment]
I tried to use a custom cleanup profile. Looks promising. But its not working properly. What i expect i the explicit behavior of the save actions plugin. For example the 'final' for method arguments are not working with the quick fix with the code cleanup. Dont know why.

Currently i use the plugin from my pull request and created a macro which executes the save actions (my committed version) and additionally save the file. Further i used this step in the key map with 'CTRL + S'. So its only be done when i hit 'CTRL + S'.

I have a problem with the current version of the save plugin in combination with the default intellj save behavior. Every time i write for example java docs and add a parameter and wait one second it will be reformatted. But iam not finished with my current work. So i have to be really fast:
save-actions

That is very annoying.

**Comment by dubreuia** [comment]
Hey @edeknede thanks for your pull request! 

But I don't see how what you did is different than pressing CTRL + S in Intellij (you can also bind "save" to something else if that's what you want).

**Comment by edeknede** [comment]
@dubreuia I like this plugin. The only option i wanted to have with my pull request is that i can execute save actions on demand. As you can see in the gif above i need sometimes the possibility to do it on demand.  Otherwise the code will be jump around.

**Comment by edeknede** [comment]
I gave this plugin to some developers and they really like the possibility to do the save actions on demand.

**Comment by jemella** [comment]
I think edeknede only wants to suppress the save actions on **autosave**.
And the disable on save and do the save actions on a specific short cut is just a workaround ;-).

**Comment by Ichag** [comment]
Hello,
I would like to see this PR merged. It adds the possibility to run the code processing on an additional trigger as an alternative to saving. 
All discussions in #54, #63 and this PR are looking for me as the try to separate the reformat and processing actions from the save event.

This PR allows exactly this.

**Comment by dubreuia** [comment]
OK thanks @jemella, the thought of disabling autosave never occured to me. The whole shortcut thing and manual saving of #54 and #63 makes sense now (thanks @Ichag)

I'll review and merge the PR, give me time I have a lot of work right now

**Comment by dubreuia** [comment]
OK I've merged this one to master, I'll test it during the week since it also contains #106 

[save-actions_0.23-RC1.jar.zip](https://github.com/dubreuia/intellij-plugin-save-actions/files/1405230/save-actions_0.23-RC1.jar.zip)

**Comment by dubreuia** [comment]
And thanks @edeknede! I really like the idea of that PR and this a nice addition to the plugin

**Pull request merged**
