### PR TITLE
Fix for #87

### PR DESCRIPTION
**Pull request by Delfic**
Added support for GLobalInspectionTool to the InspectionProcessor
Replaced SuppressionAnnotationInspection for RedundantSuppressInspection in the java/ProcessorFactory.java

### CODE REVIEW

**Comment by dubreuia** [comment]
Merged

**Comment by dubreuia** [comment]
Not good

    null
    java.lang.NullPointerException
	at com.intellij.codeInspection.InspectionEngine$2.visitElement(InspectionEngine.java:227)
	at com.intellij.codeInspection.reference.RefVisitor.visitFile(RefVisitor.java:29)
	at com.intellij.codeInspection.reference.RefFileImpl.b(RefFileImpl.java:52)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:879)
	at com.intellij.codeInspection.reference.RefFileImpl.accept(RefFileImpl.java:52)
	at com.intellij.codeInspection.InspectionEngine.runInspectionOnFile(InspectionEngine.java:219)
	at com.dubreuia.processors.java.InspectionProcessor$InspectionWriteQuickFixesAction.run(InspectionProcessor.java:92)
	at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:182)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:109)
	at com.intellij.openapi.command.WriteCommandAction$4.run(WriteCommandAction.java:157)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:119)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:160)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:104)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:82)
	at com.dubreuia.processors.java.InspectionProcessor$1.run(InspectionProcessor.java:63)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Delfic** [comment]
That line is not supposed to be executed...
`var5 = inspect(Collections.singletonList((LocalInspectionToolWrapper)toolWrapper), file, inspectionManager, false, false, new EmptyProgressIndicator());`

**Comment by Delfic** [comment]
That line is not supposed to be executed
`var5 = inspect(Collections.singletonList((LocalInspectionToolWrapper)toolWrapper), file, inspectionManager, false, false, new EmptyProgressIndicator());`

This should not run on the new inspections since it's no longer a LocalInspectionToolWrapper

There's a return in a previous if statement that should prevent the flow to reach said line.

**Comment by dubreuia** [comment]
I modified your code maybe I made a mistake, I'll check it out but I don't have time now

**Comment by dubreuia** [comment]
I can't find why it doesn't work, I've reverted the change on master, you'll need to do a new PR

**Comment by Delfic** [comment]
But what exactly did you change? I'd like to submit code that doesn't need change.

**Comment by dubreuia** [comment]
Check branch Delfic-fix-for-#87

**Pull request merged**
